### ISSUE TITLE
Bug in parsing service names

### ISSUE THREAD

**Issue by aint** [aint/octopus-autoconfiguration#1]
The following config

```yml
integration:
    services:
        pp-customers:
            url: http://localhost:8099
            logs.enable: true
```

causes false detecting of two services:

```
pp-customers
pp-customers.logs
```
